# Generated by Django 4.1.2 on 2022-10-14 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100, unique=True)),
                (
                    "Manager",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                ("sprint_id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100, unique=True)),
                ("Start_date", models.DateField(blank=True, null=True)),
                ("End_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("ticket_id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=300, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reporter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint_id",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.sprint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="sprint_id",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="SprintValue",
                to="project.sprint",
            ),
        ),
    ]
